aws/amazon-s3-encryption-client-java

src/main/java/software/amazon/encryption/s3/S3AsyncEncryptionClient.java
Build failed due to illegal javadoc synax (`<br/>`) - this replaces instances thereof with `<p>` tags.
=> fix: remove illegal javadoc syntax

src/main/java/software/amazon/encryption/s3/S3AsyncEncryptionClient.java
Removes illegally used `</p>` tags. They're allowed elsewhere but are apparently illegal in their former usage. 
=> fix: remove illegal javadoc tags

cfn/release.yml, look_4_version.sh
* Adds a missing SecretsManager permission to CloudFormation (which was manually added during the 3.0.0 release)
* Removes an extraneous `:jar` from the `look_4_artifact.sh` script. From the build output, this was running:
```
[INFO] Resolving software.amazon.encryption.s3:amazon-s3-encryption-client-java:jar:jar with transitive dependencies
4289
``` 
Removing the extra `:jar` succeeds in resolution. 
=> chore: fix some issues with release

src/main/java/software/amazon/encryption/s3/internal/ApiNameVersion.java
*Issue #, if available:* https://github.com/aws/amazon-s3-encryption-client-java/issues/158
In response to https://github.com/aws/amazon-s3-encryption-client-java/issues/158, check if the `InputStream` instance is `null` to avoid the ensuing NPE in `properties.load()` when it is.  
=> fix: null check for InputStream in ApiNameVersion

src/main/java/software/amazon/encryption/s3/S3EncryptionClient.java
Create the default wrapped clients only if they have not been specified explicitly.
S3Client.create or S3AsyncClient.create can fail in restrictive environments because they attempt to load profiles and credentials from disk, thus requiring java.io.FilePermission.
This patch moves these calls from the class initializer to the build method, so users can prevent the calls by passing their own wrapped clients.
For context: we want to use S3EncryptionClient in an Elasticsearch plugin. Plugins aren't allowed to access arbitrary files such as $HOME/.aws/credentials by default.
=> Create default wrapped clients only if necessary.

.github/workflows/build.yml, README.md
Previously, the CI used hard-coded AWS resource identifiers to run against, which makes running CI in a fork of the repo functionally impossible. 
This change moves the CI to use the repository's Action variables to specify the resources, so that forks can configure their own AWS resources. 
This _does not_ allow execution of 3p PRs against the upstream repo when the submitting fork has not gone through the setup process. 
=> chore: allow CI to run in forks

.github/workflows/build.yml, .github/workflows/ci-workflow.yml, cfn/release.yml, src/main/java/software/amazon/encryption/s3/materials/AesKeyring.java, src/main/java/software/amazon/encryption/s3/materials/DataKeyStrategy.java, src/main/java/software/amazon/encryption/s3/materials/EncryptDataKeyStrategy.java, src/main/java/software/amazon/encryption/s3/materials/GenerateDataKeyStrategy.java, src/main/java/software/amazon/encryption/s3/materials/KmsKeyring.java, src/main/java/software/amazon/encryption/s3/materials/RsaKeyring.java, src/main/java/software/amazon/encryption/s3/materials/S3Keyring.java, src/test/java/software/amazon/encryption/s3/ParameterMalleabilityTest.java, src/test/java/software/amazon/encryption/s3/S3EncryptionClientCompatibilityTest.java, src/test/java/software/amazon/encryption/s3/S3EncryptionClientStreamTest.java, src/test/java/software/amazon/encryption/s3/S3EncryptionClientTest.java
- Refactor `KmsKeyring` to use `GenerateDataKey` instead of `Encrypt`
- Update CloudFormation template, to allow IAM Role to remove `Encrypt` and only perform `GenerateDataKey` operation.
- Update CI Workflow to Run CI tests parallel and daily.
=> feat: Refactor `KmsKeyring` to use `GenerateDataKey` instead of `Encrypt`

src/main/java/software/amazon/encryption/s3/materials/AesKeyring.java, src/main/java/software/amazon/encryption/s3/materials/RsaKeyring.java, src/main/java/software/amazon/encryption/s3/materials/S3Keyring.java
- Throw a warn against use of Encryption Context for non-KmsKeyring's (i.e AesKeyring or RsaKering).
=> chore: warn against use of Encryption Context for non-kms keyrings.

codebuild/release/version.yml
Release failed:
```
node version >=20.8.1 is required. Found v18.19.0.
```
This updates the node version we install during the `version` step. 
=> chore: update node version in version step

src/examples/java/software/amazon/encryption/s3/examples/RangedGetExample.java, src/main/java/software/amazon/encryption/s3/legacy/internal/RangedGetUtils.java, src/test/java/software/amazon/encryption/s3/S3EncryptionClientRangedGetCompatibilityTest.java, src/test/java/software/amazon/encryption/s3/legacy/internal/RangedGetUtilsTest.java
- Adjust range regex to allow queries specifying only start index without specifying the end index, returns object from start index to end of stream.
=> chore: modify range to allow queries specifying only the start index

README.md
See [#186](https://github.com/aws/amazon-s3-encryption-client-java/issues/186#issuecomment-1973016669) for details.
=> docs(README): detail no unencrypted pass through

src/main/java/software/amazon/encryption/s3/S3AsyncEncryptionClient.java, src/main/java/software/amazon/encryption/s3/materials/KmsKeyring.java
- https://github.com/aws/amazon-s3-encryption-client-java/issues/183
- Create `KmsClient` and `S3AsyncClient` only if not provided in Builder.
=> fix: create clients only if necessary

src/main/java/software/amazon/encryption/s3/internal/CipherSubscriber.java, src/main/java/software/amazon/encryption/s3/legacy/internal/AdjustedRangeSubscriber.java, src/test/java/software/amazon/encryption/s3/S3AsyncEncryptionClientTest.java, src/test/java/software/amazon/encryption/s3/utils/TinyBufferAsyncRequestBody.java, src/test/java/software/amazon/encryption/s3/utils/TinyBufferSubscriber.java
*Issue #, if available:* https://github.com/aws/amazon-s3-encryption-client-java/issues/185
*Description of changes:* The current implementation of the `CipherSubscriber` incorrectly assumes that the incoming `ByteBuffer` will only contain fewer bytes than the block cipher when it is the final block. In fact, the incoming `ByteBuffer` could have fewer bytes in cases where e.g. the networking conditions are poor. As a result, the `CipherSubscriber` may erroneously call `onComplete()` partway through the operation, which then fails due to contentLength mismatch. Additionally, as pointed out in https://github.com/aws/amazon-s3-encryption-client-java/issues/185, the `CipherSubscriber` may instead throw a NPE when `amountToReadFromByteBuffer` is greater than the block size. 
This PR fixes both …
=> fix: do not signal onComplete when the incoming buffer length is less than the cipher block

SUPPORT_POLICY.rst
*Description of changes:* S3EC Java v3 is missing a support policy. Note that the v1/v2 clients are part of the AWS SDK for Java v1, which is now in maintenance mode and will be moving to end of support at the end of 2025: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/. 
=> chore: add support policy

src/test/java/software/amazon/encryption/s3/utils/BoundedStreamBufferer.java
*Issue #, if available:* 
No issue, but see https://github.com/aws/amazon-s3-encryption-client-java/actions/runs/9288503510/job/25560124190 for failed CI run 
*Description of changes:* 
When the `inputLength` in the stream tests is equal or less than 8, the `bufferSize` parameter gets set to 0 which, due to how the InputStreamSubscriber is implemented, becomes an AssertionError later on.
The easiest fix is to set the the bufferSize to 1 in BoundedStreamBufferer; this retains the spirit of the utility, which is to read the stream chunk by chunk such that the entire stream isn't read all at once.
=> chore: set bufferSize to 1 when bufferSize is less than or equal to 0 is in BoundedStreamBufferer

src/main/java/software/amazon/encryption/s3/internal/ContentMetadataStrategy.java, src/main/java/software/amazon/encryption/s3/materials/RsaKeyring.java, src/test/java/software/amazon/encryption/s3/S3EncryptionClientRangedGetCompatibilityTest.java
* Remove incorrect check in RSAKeyring
Note: The new tests fail if the check is present.
=> fix: Ranged gets with RSA keys

.github/workflows/build.yml, README.md, cfn/S3EC-GitHub-CF-Template.yml, pom.xml, src/examples/java/software/amazon/encryption/s3/examples/AsyncClientExample.java, src/examples/java/software/amazon/encryption/s3/examples/ClientConfigurationExample.java, src/examples/java/software/amazon/encryption/s3/examples/PartialKeyPairExample.java, src/main/java/software/amazon/encryption/s3/S3AsyncEncryptionClient.java, src/main/java/software/amazon/encryption/s3/S3EncryptionClient.java, src/test/java/software/amazon/encryption/s3/S3AsyncEncryptionClientTest.java, src/test/java/software/amazon/encryption/s3/S3EncryptionClientCompatibilityTest.java, src/test/java/software/amazon/encryption/s3/S3EncryptionClientRangedGetCompatibilityTest.java, src/test/java/software/amazon/encryption/s3/S3EncryptionClientTest.java, src/test/java/software/amazon/encryption/s3/examples/ClientConfigurationExampleTest.java, src/test/java/software/amazon/encryption/s3/utils/S3EncryptionClientTestResources.java
*Issue #, if available:* https://github.com/aws/amazon-s3-encryption-client-java/issues/226
*Description of changes:* Adds "top-level" client configuration options to the S3 Encryption Client. This lets customers set configuration, e.g. credentials or region in one place which is then propagated to each of the "inner" clients used by the S3EC. 
=> feat: allow S3EncryptionClient and S3AsyncEncryption Client to be configured

cfn/release.yml, codebuild/release/release-prod.yml, codebuild/release/release-staging.yml, codebuild/release/validate-staging.yml
#382 Added resources for tests.
Add these resources to the release process.
=> chore: Update Release CFN

codebuild/release/javadoc.yml
This step failed during the latest release. I ran it locally and it seems the path which javadocs are built to has changed. 
=> chore: fix release javadocs

src/main/java/software/amazon/encryption/s3/S3AsyncEncryptionClient.java, src/main/java/software/amazon/encryption/s3/S3EncryptionClient.java, src/test/java/software/amazon/encryption/s3/S3AsyncEncryptionClientTest.java, src/test/java/software/amazon/encryption/s3/S3EncryptionClientTest.java
In https://github.com/aws/amazon-s3-encryption-client-java/pull/328, the ability to configure the S3EncryptionClient and S3AsyncEncryptionClient's inner clients using the "top-level" builder was added. However, this was done based off of the more generic SDK client builder interface and thus omitted some other client configuration options specific to S3. This PR adds those extra S3-specific options to the top-level S3EC / S3AsyncEC builder. 
=> fix: introduce S3-specific client configuration to top-level configuration

pom.xml
*Issue #, if available:* https://github.com/aws/amazon-s3-encryption-client-java/issues/397
KMS classes are required at runtime.
Thus, the KMS dependency is not optional.
Closes #398 
=> fix: KMS Dependency is required

pom.xml, src/main/java/software/amazon/encryption/s3/internal/CipherAsyncRequestBody.java, src/main/java/software/amazon/encryption/s3/internal/PutEncryptedObjectPipeline.java, src/test/java/software/amazon/encryption/s3/S3EncryptionClientStreamTest.java
Throw an exception for unbounded async streams.
Also updates AWS SDK dependencies,
and some minor formatting fixes. 
=> fix: unbounded streams are not supported

src/main/java/software/amazon/encryption/s3/internal/ContentMetadataDecodingStrategy.java, src/test/java/software/amazon/encryption/s3/S3EncryptionClientCompatibilityTest.java
*Issue #, if available:* n/a
*Description of changes:* Apparently, in v2, the client would default to the empty map `{}` when the material description is not present. This is an edge case, but in the interest of being as compatible as possible, v3 will do the same. 
=> fix: treat null matdesc as empty

pom.xml, src/main/java/software/amazon/encryption/s3/S3EncryptionClientException.java
S3EncryptionClientException loses type due to missing builder in AWS SDK. This PR fixes it.
Fixes https://github.com/aws/amazon-s3-encryption-client-java/issues/449
=> fix: add builders to S3EncryptionClientException class

src/main/java/software/amazon/encryption/s3/internal/CipherSubscriber.java, src/main/resources/log4j.properties, src/test/java/software/amazon/encryption/s3/S3AsyncEncryptionClientTest.java, src/test/java/software/amazon/encryption/s3/S3EncryptionClientRangedGetCompatibilityTest.java, src/test/java/software/amazon/encryption/s3/utils/TinyBufferAsyncRequestBody.java
=> fix: fix CipherSubscriber to only call onNext once per request

src/main/java/software/amazon/encryption/s3/internal/ConvertSDKRequests.java, src/main/java/software/amazon/encryption/s3/internal/UploadObjectObserver.java, src/test/java/software/amazon/encryption/s3/S3EncryptionClientMultipartUploadTest.java, src/test/java/software/amazon/encryption/s3/internal/ConvertSDKRequestsTest.java
All possible values of a PutObjectRequest need to be supported when enabling multiparty put object.
This PR adds support and the S3EC will now fail closed in the case of new options. This is preferred to silently dropping the value.
This is a fix for: #457
=> fix: Support all PutObjectRequest fields

src/main/java/software/amazon/encryption/s3/internal/ConvertSDKRequests.java
Add more details to the error message in #458.
This adds workaround suggestions and more details.
=> fix: Add details to error message

src/main/java/software/amazon/encryption/s3/S3AsyncEncryptionClient.java, src/test/java/software/amazon/encryption/s3/S3AsyncEncryptionClientTest.java
The async client does not support "low-level" multipart uploads via CreateMPU/UploadPart/CompleteMPU. However, these APIs are accessible through the delegate client, which is misleading. This change overrides the unsupported operations and throws exceptions accordingly. 
This MAY break some customers, however, it is safer that way as otherwise objects are uploaded in plaintext. 
=> fix: disable low-level Multipart Upload in Async client

src/main/java/software/amazon/encryption/s3/S3EncryptionClient.java, src/main/java/software/amazon/encryption/s3/internal/ConvertSDKRequests.java, src/main/java/software/amazon/encryption/s3/internal/UploadObjectObserver.java, src/test/java/software/amazon/encryption/s3/S3EncryptionClientMultipartUploadTest.java, src/test/java/software/amazon/encryption/s3/internal/ConvertSDKRequestsTest.java
=> fix: support PutObjectResponse fields

CHANGELOG.md, pom.xml
This reverts commit e052b6785fe5ed0814aeb143154355350879de02.
=> revert: "Amazon S3 Encryption Client 3.3.5 Release -- 2025-05-20"

src/main/java/software/amazon/encryption/s3/S3EncryptionClient.java, src/main/java/software/amazon/encryption/s3/internal/MultipartUploadObjectPipeline.java, src/test/java/software/amazon/encryption/s3/S3EncryptionClientTest.java
*Description of changes:* Update annotations to reflects some minor spec changes.
=> chore: move spec submodule to master, update annotations

Makefile, compliance_exceptions/s3-kms-keyring.txt, src/main/java/software/amazon/encryption/s3/S3EncryptionClient.java, src/main/java/software/amazon/encryption/s3/internal/GetEncryptedObjectPipeline.java, src/main/java/software/amazon/encryption/s3/internal/MultipartUploadObjectPipeline.java, src/main/java/software/amazon/encryption/s3/materials/Keyring.java, src/main/java/software/amazon/encryption/s3/materials/KmsKeyring.java, src/main/java/software/amazon/encryption/s3/materials/S3Keyring.java, src/test/java/software/amazon/encryption/s3/S3EncryptionClientTest.java
Adds spec for Keyring, S3Keyring, and KmsKeyring. 
Also fixes some errors from the previous PR. 
Spec repo PR: https://github.com/awslabs/aws-encryption-sdk-specification/pull/306
=> chore(spec): add spec and Duvet annotations for KmsKeyring
